### ISSUE TITLE
Crossed out previous location

### ISSUE THREAD

**Issue by carsonbird** [adrianocola/spyfall#137]
I don't know if this is a feature, but it appears that the game initiator is able to see that the previous location is no longer a valid location for the current round (the previous location is crossed out from their view). This is not the case in the standard player's UI.

**Comment by adrianocola** [comment]
Fixed that one! Now all players should see the last location crossed out.

**Comment by carsonbird** [comment]
Hey, thanks. This is a really neat project - thanks for building it:)
