### ISSUE TITLE
Cant Create a Room

### ISSUE THREAD

**Issue by Private117** [adrianocola/spyfall#157]
I tryed to Create a Room with Chrome and it just gave me a Error. Then i Disabled any Adblock and pi-hole without no use. Switching to fresh Installed Firefox, without any addons or anything, same result. 

Lastly tryed it with Edge and suddenly it worked. Something seems to be wrong on the other Browsers.

EDIT: Seems to be a Problem with kaspersky Internet Security tho

**Comment by Private117** [comment]
EDIT2: Seems not to be a Problem with Kaspersky... It just works on icognito Mode but not in normal Chrome (with and without kaspersky)

**Comment by adrianocola** [comment]
It is working fine for me, on all browsers. The chrome console shows anything?

**Comment by Private117** [comment]
vendor.3bb900dcec472e72498f.chunk.js:1 Error: Reference.update failed: First argument contains undefined in property 'rooms.GMY5S.gameLocations.N3oP6EfK'
    at ae (main.a2d9841e9be796a290e4.js:85)
    at main.a2d9841e9be796a290e4.js:85
    at L (main.a2d9841e9be796a290e4.js:68)
    at ae (main.a2d9841e9be796a290e4.js:85)
    at main.a2d9841e9be796a290e4.js:85
    at L (main.a2d9841e9be796a290e4.js:68)
    at se (main.a2d9841e9be796a290e4.js:85)
    at t.update (main.a2d9841e9be796a290e4.js:201)
    at Oe (3.a09237eeda9f0a35089e.chunk.js:1)
    at 3.a09237eeda9f0a35089e.chunk.js:1

**Comment by adrianocola** [comment]
Found the issue and released a new version! Should be working now!
