### ISSUE TITLE
Replace the spy icon with "Role: Spy"

### ISSUE THREAD

**Issue by Chdata** [adrianocola/spyfall#159]
It'd allow us to do ??? as a location with every role as Spy without giving away what's going on that round.

It would also be less confusing for new players:

https://youtu.be/ZZYIxQpfz7s?t=444

**Comment by MyOtheHedgeFox** [comment]
I second that request wholeheartedly!

On 1/25/20, Chdata <notifications@github.com> wrote:
> It'd allow us to do ??? as a location with every role as Spy without giving
> away what's going on that round.
>
> It would also be less confusing for new players:
>
> https://youtu.be/ZZYIxQpfz7s?t=444
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/adrianocola/spyfall/issues/159


-- 
With respect and care,
 Danila E.

**Comment by adrianocola** [comment]
So you want to have the possibility to have a location where everyone thinks they are a spy? That's interesting. Maybe would be better to allow a custom location to treat every role as a spy? (keeping the spy icon)

**Comment by MyOtheHedgeFox** [comment]
Could be that too – including that as an optional on-or-off variant
would be pretty kickass!
_

Speaking of on-or-off homerules:
There is also a popular homerule that replaces the Spy (or Spies) with
a card from a different location (i.e. the handout for 7 players may
include 6 people from School and 1 from the Space Station – and a
handout for 9 players may include 7 from Bank, 1 from Beach and 1 from
Church).
The goal is the same – figure out where the majority is located, with
the added difficulty of possibly realizing you’re the odd one(s) out.
I'm not sure how easy or hard it will be to include this one, but
that's pretty much the only other big thing that's missing in the
Adrianocola App!

Here's a BGG forum link for more info:
boardgamegeek.com/thread/1438851/no-one-knows-if-he-spy-or-not
_

On an added note, Adriano, do you have a Patreon page or something like that?
I've been using your app extensively for teaching the game to the
newbies - the option to reduce the number of starting locations easily
is AMAZING.
Thank you so very much for updating the game regularly like that, and
have a warm hug from Russia! =)

On 1/26/20, Adriano <notifications@github.com> wrote:
> So you want to have the possibility to have a location where everyone thinks
> they are a spy? That's interesting. Maybe would be better to allow a custom
> location to treat every role as a spy? (keeping the spy icon)
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/adrianocola/spyfall/issues/159#issuecomment-578499613


-- 
With respect and care,
 Danila E.

**Comment by adrianocola** [comment]
I'll try to add those new modes. Should not be that hard.

I have a [Patreon](https://www.patreon.com/mrpg), but for another product, mRPG ([Android](https://play.google.com/store/apps/details?id=com.adrianocola.mrpg&hl=ru) and [iOS](https://apps.apple.com/ru/app/mrpg/id1330423639) app to play text-based tabletop role-playing games like D&D). But you can help there, if you want! Thank you!

**Comment by adrianocola** [comment]
@MyOtheHedgeFox  I just added the custom location option to make all players spy at that location. Next weekend I will work on the other variant.

**Comment by Chdata** [comment]
Thank you so much! I got the idea from reddit haha.

**Comment by MyOtheHedgeFox** [comment]
Thank you very very VERY much for that – and thanks for the Patreon link!

On 2/5/20, Chdata <notifications@github.com> wrote:
> Thank you so much! I got the idea from reddit haha.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/adrianocola/spyfall/issues/159#issuecomment-582231357


-- 
With respect and care,
 Danila E.

**Comment by pmsteil** [comment]
> @MyOtheHedgeFox I just added the custom location option to make all players spy at that location. 

I don't see this feature on the spyfall.adrianocola.com version - has it been deployed there, or did I miss it?  

Thanks!

**Comment by MyOtheHedgeFox** [comment]
You get this option when you create a custom location. See the tickbox
in the lower part of this screenshot:

https://i.imgur.com/lEMBF3s.png

On 4/29/20, Patrick Steil <notifications@github.com> wrote:
>> @MyOtheHedgeFox I just added the custom location option to make all
>> players spy at that location.
>
> I don't see this feature on the spyfall.adrianocola.com version - has it
> been deployed there, or did I miss it?
>
> Thanks!
>
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/adrianocola/spyfall/issues/159#issuecomment-621355323


-- 
With respect and care,
 Danila E.
