### ISSUE TITLE
What's required for this to run?

### ISSUE THREAD

**Issue by Samuelote** [adrianocola/spyfall#164]
I would love to contribute to this project, if @adrianocola is open to that. However, I am having trouble getting the app up and running. I mostly want to work on the front end, so I'm not sure if there is a dev API set up or if I need to run a local instance of the back end. That would be fine but I'm just unsure on how to get everything going (i.e. how to configure my .env etc). If I did miss any instructions on this, I apologize. If you guys are open to contributions, do you think you could provide some basic instructions on how to get the repo running locally? 

Thanks in advance!

P.S. I did see there was closed issue on this from 2015, but it seemed outdated.

**Comment by adrianocola** [comment]
Just updated the README with instructions on how to run the project locally. Let me know if you have any issues

**Comment by Samuelote** [comment]
Thank you!
