### ISSUE TITLE
My friends can't see the list of the Locations

### ISSUE THREAD

**Issue by stefanbencina** [adrianocola/spyfall#169]
Hello everybody,
I've got this issue: when I play Spyfall with my friends I am the one who creates the room but I'm also the only one who can see the list of the Locations of the game. My friends can just see their role and the Location of the match, but they don't have the list.
We usually play in Italian, but I tried also in English and it didn't change. 
We all play from Mobile phones, but I don't thik that this is the problem.
Can anybody help me?

**Comment by adrianocola** [comment]
Just fixed this! Refresh your browser and everything should be fine now

**Comment by stefanbencina** [comment]
Hi adrianocola, thank you so much!!!
I would like to ask you something else, when I played it some months ago the game when started was showing the name of the person who will start to ask questions, and it was also a complete list of the partecipants. Can you fix it please?
