### ISSUE TITLE
Localization icon broken

### ISSUE THREAD

**Issue by tannerkrewson** [adrianocola/spyfall#173]
<img width="241" alt="Capture" src="https://user-images.githubusercontent.com/8444595/79608129-0c7ccf80-80ba-11ea-81a8-145a8df493a1.PNG">
<img width="568" alt="2" src="https://user-images.githubusercontent.com/8444595/79608131-0dadfc80-80ba-11ea-8e9f-4a83c81b9031.PNG">

**Comment by tannerkrewson** [comment]
looks fixed on my end!

**Comment by adrianocola** [comment]
Yeah, the crowdin badge service was down for some reason. Now it is working!
