### ISSUE TITLE
Importing Custom Locations

### ISSUE THREAD

**Issue by Ludicrant** [adrianocola/spyfall#19]
I tried importing custom locations to my phone, a loading icon shows yet nothing comes up

**Comment by adrianocola** [comment]
I changed the exported locations mechanism today, can you try again? ( You need export the locations again)

**Comment by Ludicrant** [comment]
sorry for late response but I tried, it didn't work. it gave me 08GV as the export and I tried to import it on my phone, it loads for half a second, then nothing happens.

Date: Tue, 8 Mar 2016 04:06:27 -0800
