### ISSUE TITLE
Cannot have more than 8 players

### ISSUE THREAD

**Issue by IzMichael** [adrianocola/spyfall#192]

**Comment by adrianocola** [comment]
Do you mean local players (clicking the button "Add Player") or remote players (joining the room)? Because I was able to add 12 players clicking the "Add Player" Button multiple times

**Comment by IzMichael** [comment]
Remote Players

**Comment by adrianocola** [comment]
I tested it again recently and was able to have more than 8 remove players at the same time in a single game (in fact, I was able to have more than 12, which should not be allowed).
