### ISSUE TITLE
App fails to compile due to missing prod.js file

### ISSUE THREAD

**Issue by Zilifant** [adrianocola/spyfall#219]
Followed the instructions and ended up with this error when trying `npm run start`:

`ERROR in ./app/env.js
Module not found: Error: Can't resolve '../env/prod' in '/Users/stuff/morestuff/spyfall/app'
 @ ./app/env.js 19:0-34 25:19-26
 @ ./app/services/firebase.js
 @ ./app/app.js
 @ multi eventsource-polyfill ./app/app.js
ℹ ｢wdm｣: Failed to compile.`

Since the repo doesn't include a prod.js the compile failed when trying to import it in `./app/env.js`. Got it working, at least in dev mode, by commenting out the logic related to prod and added `const env = devEnv`.

**Comment by adrianocola** [comment]
Now webpack that require and make available for the app the right config file!
