### ISSUE TITLE
Two issues with import / export

### ISSUE THREAD

**Issue by Infi220** [adrianocola/spyfall#85]
Would it be possible to implement import of XML or text file?

There are two big problems with the current implementation:
1) It is a pain to add/edit a large number of locations and roles if they are in individual text fields as opposed to one text file where I could easily copy, paste and sort
2) The export of a 4 letter code is not reliable. Last week I created a custom list, exported it and got a code XUT4. Today I met friends for gaming but when I entered the code and clicked Import the button changed to red with the text "Error!". I tried on three different devices with the same result. So, it looks like my locations have been purged from the server for some reason. 

Implementing the import of an external XML or text file would solve both of the above problems.

**Comment by adrianocola** [comment]
The import/export feature was intended to be used only as a fast way to sync locations between devices, and not a real backup/restore solution. The server keeps the exported list for [only 7 days](https://github.com/adrianocola/spyfall/blob/945db27187181fce12b4f7edb6da8933ecfa0b2e/app.js#L124).

But I think I'll add two more buttons to download a upload a list of locations (JSON).

**Comment by adrianocola** [comment]
Added the buttons! @Infi220, can you check it out?

**Comment by Infi220** [comment]
This new feature works great, thank you! It also allows quick editing of the list in a text editor. I'm only wondering why role8 is after role 10 in the json file. It's not a big deal, just something to watch out for when people edit the text manually.
