### ISSUE TITLE
What is required for this to run?

### ISSUE THREAD

**Issue by chrom3** [adrianocola/spyfall#9]
What exactly does the server need to run for it to work?

I can't get it to work, I can get the interface and everything but it won't create rooms.

**Comment by adrianocola** [comment]
To run a local version you will need nodejs and redis. Install both, run redis (use the default port) and start the app:

```shell
   git clone git@github.com:adrianocola/spyfall.git
   cd spyfall
   npm install
   node app.js
```

The app will be available at http://localhost:4000
